name: Build & Publish

on:
  workflow_dispatch:
  push:
    branches: ["feature-**", "fix-**", "dev-**", "pr-**", "staging", "master"]
    tags: ["**"]
  schedule:
    # At 02:30 on Saturday
    - cron: "30 2 * * 6"

jobs:
  build_docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    strategy:
      matrix:
        base-image:
          ["python:3.12-trixie", "ghcr.io/tvheadend/tvheadend:edge-debian"]

    steps:
      # ---
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # ---
      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 #v3.6.0

      # ---
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6524bf65af31da8d45b59e8c27de4bd072b392f5 #v3.8.0

      # ---
      - name: Available platforms
        if: success()
        run: echo ${{ steps.buildx.outputs.platforms }}

      # ---
      - name: Prepare
        if: success()
        id: prepare
        run: |
          echo "GITHUB_REF:${GITHUB_REF}"
          echo "GITHUB_REPOSITORY:${GITHUB_REPOSITORY}"
          VERSION_TAG=${GITHUB_REF#refs/*/}
          SHA_SHORT="${GITHUB_SHA::7}"
          ORG=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

          SERVICE_NAME=headendarr-lite
          if [[ "${{ matrix.base-image }}" == *"tvheadend"* ]]; then
            SERVICE_NAME=headendarr
          fi
          DOCKER_HUB_IMAGE=docker.io/josh5/${SERVICE_NAME:?}
          GHCR_IMAGE=ghcr.io/${ORG:?}/${SERVICE_NAME:?}

          # Get version from frontend/package.json
          APP_VERSION=$(jq -r .version frontend/package.json)
          echo "app_version:${APP_VERSION}"
          echo "app_version=${APP_VERSION}" >> $GITHUB_OUTPUT

          DOCKER_TAGS=""
          DOCKER_PUSH="false"
          CREATE_GIT_TAG="false"

          if [[ ${GITHUB_REF} == refs/heads/master ]]; then
            DOCKER_PUSH="true"
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:latest,${GHCR_IMAGE}:latest,"
            
            # Check if this version already has a tag
            if ! git rev-parse "v${APP_VERSION}" >/dev/null 2>&1; then
              echo "New version detected: v${APP_VERSION}"
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:${APP_VERSION},${GHCR_IMAGE}:${APP_VERSION},"
              CREATE_GIT_TAG="true"
            fi
          elif [[ ${GITHUB_REF} == refs/heads/staging ]]; then
            DOCKER_PUSH="true"
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:staging,${GHCR_IMAGE}:staging,"
          elif [[ ${GITHUB_REF} == refs/heads/dev-* ]]; then
            DOCKER_PUSH="true"
            DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:${VERSION_TAG},${GHCR_IMAGE}:${VERSION_TAG},"
          elif [[ ${GITHUB_REF} == refs/tags/* ]]; then
            DOCKER_PUSH="true"
            VERSION=${GITHUB_REF#refs/tags/}
            if [[ ${VERSION} =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}[-\w]*$ ]]; then
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:${VERSION},${GHCR_IMAGE}:${VERSION},"
              DOCKER_TAGS="${DOCKER_TAGS}${DOCKER_HUB_IMAGE}:latest,${GHCR_IMAGE}:latest,"
            fi
          elif [[ ${GITHUB_REF} == refs/pull/* ]]; then
            PR_NUMBER=$(echo ${GITHUB_REF} | cut -d'/' -f3)
            # For PR builds, only tag the GHCR image.
            DOCKER_TAGS="${GHCR_IMAGE}:pr-${PR_NUMBER},"
          fi

          echo "Build: [$(date +"%F %T")] [${GITHUB_REF_NAME}] [${GITHUB_SHA}]" > ./docker/overlay/version.txt
          cat ./docker/overlay/version.txt

          echo "docker_hub_image:${DOCKER_HUB_IMAGE:?}"
          echo "docker_hub_image=${DOCKER_HUB_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "ghcr_image:${GHCR_IMAGE:?}"
          echo "ghcr_image=${GHCR_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "service_name:${SERVICE_NAME:?}"
          echo "service_name=${SERVICE_NAME:?}" >> $GITHUB_OUTPUT

          echo "docker_image:${DOCKER_HUB_IMAGE:?}"
          echo "docker_image=${DOCKER_HUB_IMAGE:?}" >> $GITHUB_OUTPUT

          echo "docker_tags:$(echo ${DOCKER_TAGS} | sed 's/,$//')"
          echo "docker_tags=$(echo ${DOCKER_TAGS} | sed 's/,$//')" >> $GITHUB_OUTPUT

          echo "docker_push:${DOCKER_PUSH:?}"
          echo "docker_push=${DOCKER_PUSH:?}" >> $GITHUB_OUTPUT

          echo "docker_build_date:${BUILD_DATE:?}" 
          echo "docker_build_date=${BUILD_DATE:?}" >> $GITHUB_OUTPUT

          echo "create_git_tag:${CREATE_GIT_TAG}"
          echo "create_git_tag=${CREATE_GIT_TAG}" >> $GITHUB_OUTPUT

      # ---
      - name: Log into GHCR registry
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ---
      - name: Log into Docker Hub registry
        if: success() && (startsWith(github.ref, 'refs/heads/') || startsWith(github.ref, 'refs/tags/'))
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 #v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ---
      - name: Docker meta
        if: success()
        id: meta
        uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 #v5.6.1
        with:
          images: |
            ${{ steps.prepare.outputs.docker_image }}
          labels: |
            maintainer=Josh.5
            source.version=${{ steps.prepare.outputs.sha_short }}
            source.project=Headendarr
            source.service=${{ steps.prepare.outputs.service_name }}
            org.opencontainers.image.title=${{ steps.prepare.outputs.service_name }}
            org.opencontainers.image.created=${{ steps.prepare.outputs.docker_build_date }}

      # ---
      - name: Build Frontend Cache
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          target: frontend_build_stage
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: "false"
          tags: |
            ${{ steps.prepare.outputs.ghcr_image }}:build-cache-frontend-build-stage
          cache-from: type=gha,scope=${{ steps.prepare.outputs.service_name }}-frontend-build-stage
          cache-to: type=gha,scope=${{ steps.prepare.outputs.service_name }}-frontend-build-stage,mode=max

      # ---
      - name: Build Backend Cache
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          target: backend_build_stage
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: "false"
          tags: |
            ${{ steps.prepare.outputs.ghcr_image }}:build-cache-backend-build-stage
          cache-from: type=gha,scope=${{ steps.prepare.outputs.service_name }}-backend-build-stage
          cache-to: type=gha,scope=${{ steps.prepare.outputs.service_name }}-backend-build-stage,mode=max

      # ---
      - name: Build Main Image
        if: success()
        uses: docker/build-push-action@b32b51a8eda65d6793cd0494a773d4f6bcef32dc #v6.11.0
        with:
          context: .
          file: docker/Dockerfile
          build-args: |
            VERSION=${{ github.sha }}
            BUILD_DATE=${{ steps.prepare.outputs.docker_build_date }}
            BASE_IMAGE=${{ matrix.base-image }}
          platforms: linux/amd64,linux/arm64
          pull: "true"
          push: ${{ steps.prepare.outputs.docker_push }}
          tags: |
            ${{ steps.prepare.outputs.docker_tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=${{ steps.prepare.outputs.service_name }}-main
            type=gha,scope=${{ steps.prepare.outputs.service_name }}-frontend-build-stage
            type=gha,scope=${{ steps.prepare.outputs.service_name }}-backend-build-stage
          cache-to: type=gha,scope=${{ steps.prepare.outputs.service_name }}-main,mode=max

      # ---
      - name: Check Tag Already Exists
        uses: mukunku/tag-exists-action@bdad1eaa119ce71b150b952c97351c75025c06a9 #v1.6.0
        id: check_tag_exists
        if: success() && github.ref == 'refs/heads/master' && matrix.base-image == 'ghcr.io/tvheadend/tvheadend:edge-debian'
        with:
          tag: "v${{ steps.prepare.outputs.app_version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # ---
      - name: Generate Tagged Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
        if: success() && github.ref == 'refs/heads/master' && matrix.base-image == 'ghcr.io/tvheadend/tvheadend:edge-debian' && steps.check_tag_exists.outputs.exists == 'false'
        with:
          name: "Release: v${{ steps.prepare.outputs.app_version }}"
          body: "Automated versioned release for Headendarr v${{ steps.prepare.outputs.app_version }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: false
          skipIfReleaseExists: true
          tag: "v${{ steps.prepare.outputs.app_version }}"
          commit: master

      # ---
      - name: Update Latest Release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 #v1.16.0
        if: success() && github.ref == 'refs/heads/master' && matrix.base-image == 'ghcr.io/tvheadend/tvheadend:edge-debian'
        with:
          name: "Latest Development Build"
          body: "Latest development release (bleeding edge) from the master branch."
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: true
          tag: latest
          commit: master
          prerelease: true
